"""Repository interface for customer service aggregate persistence."""
from typing import Optional, Protocol

from app.domains.customer_service.entity import CustomerServiceMessage, CustomerServiceTicket
from app.domains.customer_service.value_objects import MessageId, TicketId


class CustomerServiceRepository(Protocol):
    async def find_ticket_by_id(self, ticket_id: TicketId) -> Optional[CustomerServiceTicket]: ...

    async def find_tickets_by_user(self, user_id: str, limit: int, offset: int) -> list[CustomerServiceTicket]: ...

    async def find_waiting_tickets(self, limit: int, offset: int) -> list[CustomerServiceTicket]: ...

    async def find_active_ticket_by_user(self, user_id: str) -> Optional[CustomerServiceTicket]: ...

    async def count_waiting_tickets(self) -> int: ...

    async def count_tickets_by_user(self, user_id: str) -> int: ...

    async def save_ticket(self, ticket: CustomerServiceTicket) -> None: ...

    async def find_messages(
        self, ticket_id: TicketId, limit: int, before_id: Optional[MessageId]
    ) -> list[CustomerServiceMessage]: ...

    async def save_message(self, message: CustomerServiceMessage) -> None: ...